# acl.auth.php
# <?php exit()?>
# Don't modify the lines above
#
# Access Control Lists
#
# Auto-generated by install script
# Date: Mon, 07 Dec 2015 13:41:30 +0000
*               @ALL          0
*               @user         8
nortal:*	@user	1
esileht	@user	1
