<?php
/*
 * Dokuwiki's Main Configuration File - Local Settings
 * Auto-generated by config plugin
 * Run for user: admin
 * Date: Mon, 15 Aug 2016 14:22:25 +0200
 */

$conf['title'] = 'kalleja';
$conf['start'] = 'frontpage';
$conf['template'] = 'dokubootstrapsimplified';
$conf['license'] = 'cc-by-sa';
$conf['useacl'] = 1;
$conf['superuser'] = '@admin';
$conf['disableactions'] = 'register';
$conf['proxy']['user'] = 'admin';
$conf['proxy']['pass'] = '<b>SzFsb0p1bGlldHQ=';

// end auto-generated content
